version: "3.8"

services:
  vulnerable-web:
    image: nginx:latest
    container_name: nginx-secure-web
    restart: unless-stopped
    ports:
      - "8080:80"
    user: "nginx"
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache/nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/usr/share/nginx/html:ro
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:true
    networks:
      - webnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.25'

  # УДАЛЕН debug-shell - SSH доступ не нужен в контейнере
  # Вместо него используйте: docker exec или kubectl exec

secrets:
  admin_password:
    external: true
    name: admin_password_prod
  db_credentials:
    external: true
    name: db_creds_prod

volumes:
  static_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./static

networks:
  webnet:
    driver: bridge